{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-corrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/corrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/corrr/corrr_{{ version }}.tar.gz
  sha256: bad90b4ec6c6d47a30fa413bd1869753a89beb79adac6b4c9d76f80bdbca4cf7

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.8.0
    - r-ggplot2 >=2.2.0
    - r-ggrepel >=0.6.5
    - r-lazyeval >=0.2.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-seriation >=1.2_0
    - r-tibble >=2.0
    - r-tidyr >=0.5.1
  run:
    - r-base
    - r-dplyr >=0.8.0
    - r-ggplot2 >=2.2.0
    - r-ggrepel >=0.6.5
    - r-lazyeval >=0.2.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-seriation >=1.2_0
    - r-tibble >=2.0
    - r-tidyr >=0.5.1

test:
  commands:
    - $R -e "library('corrr')"           # [not win]
    - "\"%R%\" -e \"library('corrr')\""  # [win]

about:
  home: https://github.com/drsimonj/corrr
  license: MIT
  summary: A tool for exploring correlations. It makes it possible to easily perform routine
    tasks when exploring correlation matrices such as ignoring the diagonal, focusing
    on the correlations of certain variables against others, or rearranging and visualising
    the matrix in terms of the strength of the correlations.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo

# Package: corrr
# Type: Package
# Version: 0.3.1
# Title: Correlations in R
# Description: A tool for exploring correlations. It makes it possible to easily perform routine tasks when exploring correlation matrices such as ignoring the diagonal, focusing on the correlations of certain variables against others, or rearranging and visualising the matrix in terms of the strength of the correlations.
# Author:  Simon Jackson [aut, cre], Jorge Cimentada [ctb], Edgar Ruiz [aut]
# Maintainer: Edgar Ruiz <edgararuiz@gmail.com>
# URL: https://github.com/drsimonj/corrr
# BugReports: https://github.com/drsimonj/corrr/issues
# Depends: R (>= 3.3.0)
# LazyData: yes
# License: MIT + file LICENSE
# RoxygenNote: 6.1.1
# Suggests: testthat (>= 1.0.2), knitr (>= 1.13), rmarkdown (>= 0.9.6), dbplyr (>= 1.2.1), DBI, RSQLite
# Imports: dplyr (>= 0.8.0), magrittr (>= 1.5), tidyr (>= 0.5.1), ggplot2 (>= 2.2.0), seriation (>= 1.2-0), lazyeval (>= 0.2.0), purrr (>= 0.2.2), tibble (>= 2.0), ggrepel (>= 0.6.5), methods (>= 3.4.3), rlang(>= 0.2.0)
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-03-05 23:50:40 UTC; edgar
# Repository: CRAN
# Date/Publication: 2019-03-06 09:50:03 UTC
