{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-corrr
  version: {{ version|replace("-", "_") }}

source:
  fn: corrr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/corrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/corrr/corrr_{{ version }}.tar.gz
  sha256: d07244c1c02e7c36211b5d5a57993a786063b1b10ef9c6ca03151a81760d1704

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr >=0.5.0
    - r-ggplot2 >=2.2.0
    - r-ggrepel >=0.6.5
    - r-lazyeval >=0.2.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-seriation >=1.2_0
    - r-tibble >=1.1
    - r-tidyr >=0.5.1
  run:
    - r-base
    - r-dplyr >=0.5.0
    - r-ggplot2 >=2.2.0
    - r-ggrepel >=0.6.5
    - r-lazyeval >=0.2.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.2
    - r-rlang >=0.2.0
    - r-seriation >=1.2_0
    - r-tibble >=1.1
    - r-tidyr >=0.5.1

test:
  commands:
    - $R -e "library('corrr')"           # [not win]
    - "\"%R%\" -e \"library('corrr')\""  # [win]

about:
  home: https://github.com/drsimonj/corrr
  license: MIT
  summary: A tool for exploring correlations. It makes it possible to easily perform routine
    tasks when exploring correlation matrices such as ignoring the diagonal, focusing
    on the correlations of certain variables against others, or rearranging and visualising
    the matrix in terms of the strength of the correlations.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - apcamargo
